<?php

namespace A2x\BlogBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class PostController__JMSInjector
{
    public static function inject($container) {
        $instance = new \A2x\BlogBundle\Controller\PostController();
        return $instance;
    }
}
