<?php

namespace Acme\StudyBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class HelloController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\StudyBundle\Controller\HelloController();
        return $instance;
    }
}
